import type { SummaryCommandInfo } from './summary-cli';

// AUTO-GENERATED by scripts/generate-summary-manifest.ts. Do not edit manually.
export const SUMMARY_COMMANDS: SummaryCommandInfo[] = [
  {
    "name": "application.create",
    "description": "Create a new application"
  },
  {
    "name": "config.set",
    "description": "Set a configuration value. Use either \"key=value\" or \"key value\" format"
  },
  {
    "name": "config.list",
    "description": "List the current configuration"
  },
  {
    "name": "config.ls",
    "description": "List the current configuration"
  },
  {
    "name": "math.add",
    "description": "Add two numbers. Use this if you and your friend both have apples, and you want to know how many apples there are in total."
  },
  {
    "name": "math.subtract",
    "description": "Subtract two numbers. Useful if you have a number and you want to make it smaller."
  },
  {
    "name": "math.multiply",
    "description": "Multiply two numbers together. Useful if you want to count the number of tiles on your bathroom wall and are short on time."
  },
  {
    "name": "math.divide",
    "description": "Divide two numbers. Useful if you have a number and you want to make it smaller and `subtract` isn't quite powerful enough for you."
  },
  {
    "name": "help.man",
    "description": "Gets the manual for a subject."
  },
  {
    "name": "test.evolution",
    "description": "Test evo"
  },
  {
    "name": "cerebro.ask"
  },
  {
    "name": "cerebro.exec"
  },
  {
    "name": "cerebro.info"
  },
  {
    "name": "cerebro.auth"
  },
  {
    "name": "seer.area.getArea"
  },
  {
    "name": "seer.area.getAreas"
  },
  {
    "name": "seer.area.saveArea"
  },
  {
    "name": "seer.area.getAreaLandmark"
  },
  {
    "name": "seer.area.createAreaLandmark"
  },
  {
    "name": "seer.area.updateAreaLandmark"
  },
  {
    "name": "seer.area.getAreaType"
  },
  {
    "name": "seer.area.createAreaType"
  },
  {
    "name": "seer.area.updateAreaType"
  },
  {
    "name": "seer.asset.getAsset"
  },
  {
    "name": "seer.asset.createAsset"
  },
  {
    "name": "seer.asset.updateAsset"
  },
  {
    "name": "seer.asset.getAssetLicense"
  },
  {
    "name": "seer.asset.createAssetLicense"
  },
  {
    "name": "seer.asset.updateAssetLicense"
  },
  {
    "name": "seer.chain.getChain"
  },
  {
    "name": "seer.chain.createChain"
  },
  {
    "name": "seer.chain.updateChain"
  },
  {
    "name": "seer.chain.getChainContract"
  },
  {
    "name": "seer.chain.createChainContract"
  },
  {
    "name": "seer.chain.updateChainContract"
  },
  {
    "name": "seer.chain.getChainToken"
  },
  {
    "name": "seer.chain.createChainToken"
  },
  {
    "name": "seer.chain.updateChainToken"
  },
  {
    "name": "seer.chain.getChainTransaction"
  },
  {
    "name": "seer.chain.createChainTransaction"
  },
  {
    "name": "seer.chain.updateChainTransaction"
  },
  {
    "name": "seer.character.getCharacterInventory"
  },
  {
    "name": "seer.character.syncCharacterInventory"
  },
  {
    "name": "seer.character.applyCharacterInventoryPatch"
  },
  {
    "name": "seer.character.setActiveCharacter"
  },
  {
    "name": "seer.character.exchangeCharacterItem"
  },
  {
    "name": "seer.character.getCharacterData"
  },
  {
    "name": "seer.character.getCharacter"
  },
  {
    "name": "seer.character.getCharacters"
  },
  {
    "name": "seer.character.saveCharacters"
  },
  {
    "name": "seer.character.updateCharacter"
  },
  {
    "name": "seer.character.getCharacterAbility"
  },
  {
    "name": "seer.character.createCharacterAbility"
  },
  {
    "name": "seer.character.updateCharacterAbility"
  },
  {
    "name": "seer.character.getCharacterAttribute"
  },
  {
    "name": "seer.character.createCharacterAttribute"
  },
  {
    "name": "seer.character.updateCharacterAttribute"
  },
  {
    "name": "seer.character.getCharacterType"
  },
  {
    "name": "seer.character.createCharacterType"
  },
  {
    "name": "seer.character.updateCharacterType"
  },
  {
    "name": "seer.character.getCharacterClass"
  },
  {
    "name": "seer.character.createCharacterClass"
  },
  {
    "name": "seer.character.updateCharacterClass"
  },
  {
    "name": "seer.character.getCharacterRace"
  },
  {
    "name": "seer.character.createCharacterRace"
  },
  {
    "name": "seer.character.updateCharacterRace"
  },
  {
    "name": "seer.character.getCharacterGender"
  },
  {
    "name": "seer.character.createCharacterGender"
  },
  {
    "name": "seer.character.updateCharacterGender"
  },
  {
    "name": "seer.character.getCharacterPersonality"
  },
  {
    "name": "seer.character.createCharacterPersonality"
  },
  {
    "name": "seer.character.updateCharacterPersonality"
  },
  {
    "name": "seer.character.getCharacterTitle"
  },
  {
    "name": "seer.character.createCharacterTitle"
  },
  {
    "name": "seer.character.updateCharacterTitle"
  },
  {
    "name": "seer.character.getCharacterFaction"
  },
  {
    "name": "seer.character.getCharacterFactions"
  },
  {
    "name": "seer.character.createCharacterFaction"
  },
  {
    "name": "seer.character.updateCharacterFaction"
  },
  {
    "name": "seer.character.getCharacterNameChoice"
  },
  {
    "name": "seer.character.createCharacterNameChoice"
  },
  {
    "name": "seer.character.updateCharacterNameChoice"
  },
  {
    "name": "seer.chat.getChatGroup"
  },
  {
    "name": "seer.chat.getChatGroups"
  },
  {
    "name": "seer.chat.createChatGroup"
  },
  {
    "name": "seer.chat.updateChatGroup"
  },
  {
    "name": "seer.chat.getChatMessage"
  },
  {
    "name": "seer.chat.getChatMessages"
  },
  {
    "name": "seer.chat.createChatMessage"
  },
  {
    "name": "seer.chat.updateChatMessage"
  },
  {
    "name": "seer.collection.getCollectibleCollection"
  },
  {
    "name": "seer.collection.createCollectibleCollection"
  },
  {
    "name": "seer.collection.updateCollectibleCollection"
  },
  {
    "name": "seer.collection.getCollectibleCardBox"
  },
  {
    "name": "seer.collection.createCollectibleCardBox"
  },
  {
    "name": "seer.collection.updateCollectibleCardBox"
  },
  {
    "name": "seer.collection.getCollectibleCardPack"
  },
  {
    "name": "seer.collection.createCollectibleCardPack"
  },
  {
    "name": "seer.collection.updateCollectibleCardPack"
  },
  {
    "name": "seer.collection.getCollectibleCard"
  },
  {
    "name": "seer.collection.createCollectibleCard"
  },
  {
    "name": "seer.collection.updateCollectibleCard"
  },
  {
    "name": "seer.core.getConversation"
  },
  {
    "name": "seer.core.createConversation"
  },
  {
    "name": "seer.core.updateConversation"
  },
  {
    "name": "seer.core.getConversations"
  },
  {
    "name": "seer.core.getConversationMessage"
  },
  {
    "name": "seer.core.getConversationMessages"
  },
  {
    "name": "seer.core.createConversationMessage"
  },
  {
    "name": "seer.core.updateConversationMessage"
  },
  {
    "name": "seer.core.claimConversationMessage"
  },
  {
    "name": "seer.core.setConversationMessageStar"
  },
  {
    "name": "seer.core.markConversationRead"
  },
  {
    "name": "seer.core.archiveReadConversations"
  },
  {
    "name": "seer.core.readAndClaimLatestMail"
  },
  {
    "name": "seer.core.distributeSantaChristmasTicketToProfile"
  },
  {
    "name": "seer.core.distributeSantaChristmasTicket"
  },
  {
    "name": "seer.core.play"
  },
  {
    "name": "seer.core.syncGetPayloadsSince"
  },
  {
    "name": "seer.core.ingestWarpFlowActivity"
  },
  {
    "name": "seer.core.getWarpFlowActivity"
  },
  {
    "name": "seer.core.updateSettings"
  },
  {
    "name": "seer.core.ask"
  },
  {
    "name": "seer.core.authorize"
  },
  {
    "name": "seer.core.getAccount"
  },
  {
    "name": "seer.core.getAccounts"
  },
  {
    "name": "seer.core.createAccount"
  },
  {
    "name": "seer.core.updateAccount"
  },
  {
    "name": "seer.core.getAchievement"
  },
  {
    "name": "seer.core.getAchievements"
  },
  {
    "name": "seer.core.createAchievement"
  },
  {
    "name": "seer.core.updateAchievement"
  },
  {
    "name": "seer.core.getAct"
  },
  {
    "name": "seer.core.getActs"
  },
  {
    "name": "seer.core.createAct"
  },
  {
    "name": "seer.core.updateAct"
  },
  {
    "name": "seer.core.getAgent"
  },
  {
    "name": "seer.core.createAgent"
  },
  {
    "name": "seer.core.updateAgent"
  },
  {
    "name": "seer.core.getApplication"
  },
  {
    "name": "seer.core.createApplication"
  },
  {
    "name": "seer.core.updateApplication"
  },
  {
    "name": "seer.core.getBadge"
  },
  {
    "name": "seer.core.createBadge"
  },
  {
    "name": "seer.core.updateBadge"
  },
  {
    "name": "seer.core.getBattlePass"
  },
  {
    "name": "seer.core.createBattlePass"
  },
  {
    "name": "seer.core.updateBattlePass"
  },
  {
    "name": "seer.core.getBiome"
  },
  {
    "name": "seer.core.createBiome"
  },
  {
    "name": "seer.core.updateBiome"
  },
  {
    "name": "seer.core.getBiomeFeature"
  },
  {
    "name": "seer.core.createBiomeFeature"
  },
  {
    "name": "seer.core.updateBiomeFeature"
  },
  {
    "name": "seer.core.getBounty"
  },
  {
    "name": "seer.core.createBounty"
  },
  {
    "name": "seer.core.updateBounty"
  },
  {
    "name": "seer.core.getCollection"
  },
  {
    "name": "seer.core.createCollection"
  },
  {
    "name": "seer.core.updateCollection"
  },
  {
    "name": "seer.core.getComment"
  },
  {
    "name": "seer.core.createComment"
  },
  {
    "name": "seer.core.updateComment"
  },
  {
    "name": "seer.core.getCommunity"
  },
  {
    "name": "seer.core.createCommunity"
  },
  {
    "name": "seer.core.updateCommunity"
  },
  {
    "name": "seer.core.getCompany"
  },
  {
    "name": "seer.core.createCompany"
  },
  {
    "name": "seer.core.updateCompany"
  },
  {
    "name": "seer.core.getData"
  },
  {
    "name": "seer.core.createData"
  },
  {
    "name": "seer.core.updateData"
  },
  {
    "name": "seer.core.getDiscussion"
  },
  {
    "name": "seer.core.createDiscussion"
  },
  {
    "name": "seer.core.updateDiscussion"
  },
  {
    "name": "seer.core.getEnergy"
  },
  {
    "name": "seer.core.getEnergies"
  },
  {
    "name": "seer.core.createEnergy"
  },
  {
    "name": "seer.core.updateEnergy"
  },
  {
    "name": "seer.core.getEvent"
  },
  {
    "name": "seer.core.createEvent"
  },
  {
    "name": "seer.core.updateEvent"
  },
  {
    "name": "seer.core.getFile"
  },
  {
    "name": "seer.core.createFile"
  },
  {
    "name": "seer.core.updateFile"
  },
  {
    "name": "seer.core.getGalaxy"
  },
  {
    "name": "seer.core.createGalaxy"
  },
  {
    "name": "seer.core.updateGalaxy"
  },
  {
    "name": "seer.core.getGuide"
  },
  {
    "name": "seer.core.createGuide"
  },
  {
    "name": "seer.core.updateGuide"
  },
  {
    "name": "seer.core.getIdea"
  },
  {
    "name": "seer.core.createIdea"
  },
  {
    "name": "seer.core.updateIdea"
  },
  {
    "name": "seer.core.getLeaderboard"
  },
  {
    "name": "seer.core.createLeaderboard"
  },
  {
    "name": "seer.core.updateLeaderboard"
  },
  {
    "name": "seer.core.getLog"
  },
  {
    "name": "seer.core.createLog"
  },
  {
    "name": "seer.core.updateLog"
  },
  {
    "name": "seer.core.getLore"
  },
  {
    "name": "seer.core.createLore"
  },
  {
    "name": "seer.core.updateLore"
  },
  {
    "name": "seer.core.getMemory"
  },
  {
    "name": "seer.core.createMemory"
  },
  {
    "name": "seer.core.updateMemory"
  },
  {
    "name": "seer.core.ingestMemoryLedgerRecord"
  },
  {
    "name": "seer.core.getMemoryLedgerRecords"
  },
  {
    "name": "seer.core.getMemoryTelemetrySummary"
  },
  {
    "name": "seer.core.getMessage"
  },
  {
    "name": "seer.core.createMessage"
  },
  {
    "name": "seer.core.updateMessage"
  },
  {
    "name": "seer.core.getMetaverse"
  },
  {
    "name": "seer.core.createMetaverse"
  },
  {
    "name": "seer.core.updateMetaverse"
  },
  {
    "name": "seer.core.getNewsArticle"
  },
  {
    "name": "seer.core.createNewsArticle"
  },
  {
    "name": "seer.core.updateNewsArticle"
  },
  {
    "name": "seer.core.getNpc"
  },
  {
    "name": "seer.core.createNpc"
  },
  {
    "name": "seer.core.updateNpc"
  },
  {
    "name": "seer.core.getOffer"
  },
  {
    "name": "seer.core.createOffer"
  },
  {
    "name": "seer.core.updateOffer"
  },
  {
    "name": "seer.core.getOmniverse"
  },
  {
    "name": "seer.core.createOmniverse"
  },
  {
    "name": "seer.core.updateOmniverse"
  },
  {
    "name": "seer.core.getOrder"
  },
  {
    "name": "seer.core.createOrder"
  },
  {
    "name": "seer.core.updateOrder"
  },
  {
    "name": "seer.core.getPayment"
  },
  {
    "name": "seer.core.createPayment"
  },
  {
    "name": "seer.core.updatePayment"
  },
  {
    "name": "seer.core.getPermission"
  },
  {
    "name": "seer.core.createPermission"
  },
  {
    "name": "seer.core.updatePermission"
  },
  {
    "name": "seer.core.getPerson"
  },
  {
    "name": "seer.core.createPerson"
  },
  {
    "name": "seer.core.updatePerson"
  },
  {
    "name": "seer.core.getPlanet"
  },
  {
    "name": "seer.core.createPlanet"
  },
  {
    "name": "seer.core.updatePlanet"
  },
  {
    "name": "seer.core.getPoll"
  },
  {
    "name": "seer.core.createPoll"
  },
  {
    "name": "seer.core.updatePoll"
  },
  {
    "name": "seer.core.getProject"
  },
  {
    "name": "seer.core.createProject"
  },
  {
    "name": "seer.core.updateProject"
  },
  {
    "name": "seer.core.getRepository"
  },
  {
    "name": "seer.core.getRepositories"
  },
  {
    "name": "seer.core.createRepository"
  },
  {
    "name": "seer.core.updateRepository"
  },
  {
    "name": "seer.core.upsertRepository"
  },
  {
    "name": "seer.core.getProductFeature"
  },
  {
    "name": "seer.core.getProductFeatures"
  },
  {
    "name": "seer.core.createProductFeature"
  },
  {
    "name": "seer.core.updateProductFeature"
  },
  {
    "name": "seer.core.upsertProductFeature"
  },
  {
    "name": "seer.core.getRepositoryCommit"
  },
  {
    "name": "seer.core.getRepositoryCommits"
  },
  {
    "name": "seer.core.createRepositoryCommit"
  },
  {
    "name": "seer.core.updateRepositoryCommit"
  },
  {
    "name": "seer.core.upsertRepositoryCommit"
  },
  {
    "name": "seer.core.getIssueEmbedding"
  },
  {
    "name": "seer.core.getIssueEmbeddings"
  },
  {
    "name": "seer.core.upsertIssueEmbedding"
  },
  {
    "name": "seer.core.upsertIssueEmbeddingsBatch"
  },
  {
    "name": "seer.core.searchIssueEmbeddings"
  },
  {
    "name": "seer.core.getProjectEmbedding"
  },
  {
    "name": "seer.core.getProjectEmbeddings"
  },
  {
    "name": "seer.core.upsertProjectEmbedding"
  },
  {
    "name": "seer.core.upsertProjectEmbeddingsBatch"
  },
  {
    "name": "seer.core.searchProjectEmbeddings"
  },
  {
    "name": "seer.core.getProductEmbedding"
  },
  {
    "name": "seer.core.getProductEmbeddings"
  },
  {
    "name": "seer.core.upsertProductEmbedding"
  },
  {
    "name": "seer.core.upsertProductEmbeddingsBatch"
  },
  {
    "name": "seer.core.searchProductEmbeddings"
  },
  {
    "name": "seer.core.getAgentEmbedding"
  },
  {
    "name": "seer.core.getAgentEmbeddings"
  },
  {
    "name": "seer.core.upsertAgentEmbedding"
  },
  {
    "name": "seer.core.upsertAgentEmbeddingsBatch"
  },
  {
    "name": "seer.core.searchAgentEmbeddings"
  },
  {
    "name": "seer.core.getSessionContext"
  },
  {
    "name": "seer.core.getSessionContexts"
  },
  {
    "name": "seer.core.upsertSessionContext"
  },
  {
    "name": "seer.core.upsertSessionContextEdge"
  },
  {
    "name": "seer.core.getActiveSessionContextsByRepoAndAgent"
  },
  {
    "name": "seer.core.getProposal"
  },
  {
    "name": "seer.core.createProposal"
  },
  {
    "name": "seer.core.updateProposal"
  },
  {
    "name": "seer.core.getQuest"
  },
  {
    "name": "seer.core.createQuest"
  },
  {
    "name": "seer.core.updateQuest"
  },
  {
    "name": "seer.core.getRating"
  },
  {
    "name": "seer.core.createRating"
  },
  {
    "name": "seer.core.updateRating"
  },
  {
    "name": "seer.core.getRealm"
  },
  {
    "name": "seer.core.getRealms"
  },
  {
    "name": "seer.core.createRealm"
  },
  {
    "name": "seer.core.updateRealm"
  },
  {
    "name": "seer.core.getRealmEvent"
  },
  {
    "name": "seer.core.getRealmEvents"
  },
  {
    "name": "seer.core.createRealmEvent"
  },
  {
    "name": "seer.core.updateRealmEvent"
  },
  {
    "name": "seer.core.getRevision"
  },
  {
    "name": "seer.core.createRevision"
  },
  {
    "name": "seer.core.updateRevision"
  },
  {
    "name": "seer.core.getReferral"
  },
  {
    "name": "seer.core.createReferral"
  },
  {
    "name": "seer.core.updateReferral"
  },
  {
    "name": "seer.core.getReview"
  },
  {
    "name": "seer.core.createReview"
  },
  {
    "name": "seer.core.updateReview"
  },
  {
    "name": "seer.core.getRole"
  },
  {
    "name": "seer.core.createRole"
  },
  {
    "name": "seer.core.updateRole"
  },
  {
    "name": "seer.core.getSeason"
  },
  {
    "name": "seer.core.createSeason"
  },
  {
    "name": "seer.core.updateSeason"
  },
  {
    "name": "seer.core.getRealmShard"
  },
  {
    "name": "seer.core.getRealmShards"
  },
  {
    "name": "seer.core.createRealmShard"
  },
  {
    "name": "seer.core.updateRealmShard"
  },
  {
    "name": "seer.core.getSession"
  },
  {
    "name": "seer.core.createSession"
  },
  {
    "name": "seer.core.updateSession"
  },
  {
    "name": "seer.core.getSolarSystem"
  },
  {
    "name": "seer.core.createSolarSystem"
  },
  {
    "name": "seer.core.updateSolarSystem"
  },
  {
    "name": "seer.core.getStar"
  },
  {
    "name": "seer.core.createStar"
  },
  {
    "name": "seer.core.updateStar"
  },
  {
    "name": "seer.core.getStash"
  },
  {
    "name": "seer.core.createStash"
  },
  {
    "name": "seer.core.updateStash"
  },
  {
    "name": "seer.core.getStock"
  },
  {
    "name": "seer.core.createStock"
  },
  {
    "name": "seer.core.updateStock"
  },
  {
    "name": "seer.core.getSuggestion"
  },
  {
    "name": "seer.core.createSuggestion"
  },
  {
    "name": "seer.core.updateSuggestion"
  },
  {
    "name": "seer.core.getTag"
  },
  {
    "name": "seer.core.createTag"
  },
  {
    "name": "seer.core.updateTag"
  },
  {
    "name": "seer.core.getTeam"
  },
  {
    "name": "seer.core.getTeams"
  },
  {
    "name": "seer.core.createTeam"
  },
  {
    "name": "seer.core.updateTeam"
  },
  {
    "name": "seer.core.getTournament"
  },
  {
    "name": "seer.core.getTournaments"
  },
  {
    "name": "seer.core.createTournament"
  },
  {
    "name": "seer.core.updateTournament"
  },
  {
    "name": "seer.core.getTrade"
  },
  {
    "name": "seer.core.getTrades"
  },
  {
    "name": "seer.core.createTrade"
  },
  {
    "name": "seer.core.updateTrade"
  },
  {
    "name": "seer.core.getUniverse"
  },
  {
    "name": "seer.core.createUniverse"
  },
  {
    "name": "seer.core.updateUniverse"
  },
  {
    "name": "seer.core.getValidator"
  },
  {
    "name": "seer.core.createValidator"
  },
  {
    "name": "seer.core.updateValidator"
  },
  {
    "name": "seer.core.getVote"
  },
  {
    "name": "seer.core.createVote"
  },
  {
    "name": "seer.core.updateVote"
  },
  {
    "name": "seer.core.getWorldEvent"
  },
  {
    "name": "seer.core.createWorldEvent"
  },
  {
    "name": "seer.core.updateWorldEvent"
  },
  {
    "name": "seer.core.getWorldRecord"
  },
  {
    "name": "seer.core.createWorldRecord"
  },
  {
    "name": "seer.core.updateWorldRecord"
  },
  {
    "name": "seer.core.info"
  },
  {
    "name": "seer.core.stats"
  },
  {
    "name": "seer.game.getGame"
  },
  {
    "name": "seer.game.getGames"
  },
  {
    "name": "seer.game.createGame"
  },
  {
    "name": "seer.game.updateGame"
  },
  {
    "name": "seer.game.getGameStat"
  },
  {
    "name": "seer.game.getGameStats"
  },
  {
    "name": "seer.game.createGameStat"
  },
  {
    "name": "seer.game.updateGameStat"
  },
  {
    "name": "seer.game.getEra"
  },
  {
    "name": "seer.game.getEras"
  },
  {
    "name": "seer.game.createEra"
  },
  {
    "name": "seer.game.updateEra"
  },
  {
    "name": "seer.game.deleteEra"
  },
  {
    "name": "seer.interface.getInterface"
  },
  {
    "name": "seer.interface.createInterface"
  },
  {
    "name": "seer.interface.updateInterface"
  },
  {
    "name": "seer.interface.deleteInterface"
  },
  {
    "name": "seer.interface.getInterfaces"
  },
  {
    "name": "seer.interface.getInterfaceGroup"
  },
  {
    "name": "seer.interface.getInterfaceGroups"
  },
  {
    "name": "seer.interface.createInterfaceGroup"
  },
  {
    "name": "seer.interface.updateInterfaceGroup"
  },
  {
    "name": "seer.interface.getInterfaceComponent"
  },
  {
    "name": "seer.interface.createInterfaceComponent"
  },
  {
    "name": "seer.interface.updateInterfaceComponent"
  },
  {
    "name": "seer.interface.publishInterface"
  },
  {
    "name": "seer.interface.deactivateInterface"
  },
  {
    "name": "seer.interface.resetInterface"
  },
  {
    "name": "seer.interface.acceptInterfaceSubmission"
  },
  {
    "name": "seer.interface.createInterfaceDraft"
  },
  {
    "name": "seer.item.getItem"
  },
  {
    "name": "seer.item.getItems"
  },
  {
    "name": "seer.item.createItem"
  },
  {
    "name": "seer.item.updateItem"
  },
  {
    "name": "seer.item.getItemAttribute"
  },
  {
    "name": "seer.item.createItemAttribute"
  },
  {
    "name": "seer.item.updateItemAttribute"
  },
  {
    "name": "seer.item.getItemTransmute"
  },
  {
    "name": "seer.item.createItemTransmute"
  },
  {
    "name": "seer.item.updateItemTransmute"
  },
  {
    "name": "seer.job.getJob"
  },
  {
    "name": "seer.job.createJob"
  },
  {
    "name": "seer.job.updateJob"
  },
  {
    "name": "seer.job.updateMetrics"
  },
  {
    "name": "seer.market.getMarket"
  },
  {
    "name": "seer.market.createMarket"
  },
  {
    "name": "seer.market.updateMarket"
  },
  {
    "name": "seer.market.getMarketPair"
  },
  {
    "name": "seer.market.createMarketPair"
  },
  {
    "name": "seer.market.updateMarketPair"
  },
  {
    "name": "seer.market.getMarketExchange"
  },
  {
    "name": "seer.market.createMarketExchange"
  },
  {
    "name": "seer.market.updateMarketExchange"
  },
  {
    "name": "seer.market.getMarketListing"
  },
  {
    "name": "seer.market.createMarketListing"
  },
  {
    "name": "seer.market.updateMarketListing"
  },
  {
    "name": "seer.market.deleteMarketListing"
  },
  {
    "name": "seer.market.getMarketListings"
  },
  {
    "name": "seer.product.getProduct"
  },
  {
    "name": "seer.product.createProduct"
  },
  {
    "name": "seer.product.updateProduct"
  },
  {
    "name": "seer.product.getProductDLC"
  },
  {
    "name": "seer.product.createProductDLC"
  },
  {
    "name": "seer.product.updateProductDLC"
  },
  {
    "name": "seer.product.getProductBundle"
  },
  {
    "name": "seer.product.createProductBundle"
  },
  {
    "name": "seer.product.updateProductBundle"
  },
  {
    "name": "seer.product.getProductReview"
  },
  {
    "name": "seer.product.createProductReview"
  },
  {
    "name": "seer.product.updateProductReview"
  },
  {
    "name": "seer.profile.setProfileMode"
  },
  {
    "name": "seer.profile.me"
  },
  {
    "name": "seer.profile.getProfile"
  },
  {
    "name": "seer.profile.getProfiles"
  },
  {
    "name": "seer.profile.createProfile"
  },
  {
    "name": "seer.profile.updateProfile"
  },
  {
    "name": "seer.profile.getProfileStats"
  },
  {
    "name": "seer.profile.updateProfileSettings"
  },
  {
    "name": "seer.raffle.getRaffle"
  },
  {
    "name": "seer.raffle.createRaffle"
  },
  {
    "name": "seer.raffle.updateRaffle"
  },
  {
    "name": "seer.raffle.getRaffleRequirement"
  },
  {
    "name": "seer.raffle.createRaffleRequirement"
  },
  {
    "name": "seer.raffle.updateRaffleRequirement"
  },
  {
    "name": "seer.raffle.getRaffleReward"
  },
  {
    "name": "seer.raffle.createRaffleReward"
  },
  {
    "name": "seer.raffle.updateRaffleReward"
  },
  {
    "name": "seer.raffle.getRaffleEntry"
  },
  {
    "name": "seer.raffle.createRaffleEntry"
  },
  {
    "name": "seer.raffle.updateRaffleEntry"
  },
  {
    "name": "seer.skill.getSkill"
  },
  {
    "name": "seer.skill.createSkill"
  },
  {
    "name": "seer.skill.updateSkill"
  },
  {
    "name": "seer.skill.deleteSkill"
  },
  {
    "name": "seer.skill.getSkillMod"
  },
  {
    "name": "seer.skill.createSkillMod"
  },
  {
    "name": "seer.skill.updateSkillMod"
  },
  {
    "name": "seer.skill.deleteSkillMod"
  },
  {
    "name": "seer.skill.getSkillClassification"
  },
  {
    "name": "seer.skill.createSkillClassification"
  },
  {
    "name": "seer.skill.updateSkillClassification"
  },
  {
    "name": "seer.skill.deleteSkillClassification"
  },
  {
    "name": "seer.skill.getSkillCondition"
  },
  {
    "name": "seer.skill.createSkillCondition"
  },
  {
    "name": "seer.skill.updateSkillCondition"
  },
  {
    "name": "seer.skill.deleteSkillCondition"
  },
  {
    "name": "seer.skill.getSkillStatusEffect"
  },
  {
    "name": "seer.skill.createSkillStatusEffect"
  },
  {
    "name": "seer.skill.updateSkillStatusEffect"
  },
  {
    "name": "seer.skill.deleteSkillStatusEffect"
  },
  {
    "name": "seer.skill.getSkillTree"
  },
  {
    "name": "seer.skill.createSkillTree"
  },
  {
    "name": "seer.skill.updateSkillTree"
  },
  {
    "name": "seer.skill.deleteSkillTree"
  },
  {
    "name": "seer.skill.getSkillTreeNode"
  },
  {
    "name": "seer.skill.createSkillTreeNode"
  },
  {
    "name": "seer.skill.updateSkillTreeNode"
  },
  {
    "name": "seer.skill.deleteSkillTreeNode"
  },
  {
    "name": "seer.video.getVideo"
  },
  {
    "name": "seer.video.createVideo"
  },
  {
    "name": "seer.video.updateVideo"
  },
  {
    "name": "seer.video.deleteVideo"
  },
  {
    "name": "seer.video.getVideoParticipant"
  },
  {
    "name": "seer.video.createVideoParticipant"
  },
  {
    "name": "seer.video.updateVideoParticipant"
  },
  {
    "name": "seer.video.deleteVideoParticipant"
  },
  {
    "name": "seer.video.getVideoDialogue"
  },
  {
    "name": "seer.video.createVideoDialogue"
  },
  {
    "name": "seer.video.updateVideoDialogue"
  },
  {
    "name": "seer.video.deleteVideoDialogue"
  },
  {
    "name": "seer.video.getVideoTranscript"
  },
  {
    "name": "seer.video.createVideoTranscript"
  },
  {
    "name": "seer.video.updateVideoTranscript"
  },
  {
    "name": "seer.video.deleteVideoTranscript"
  },
  {
    "name": "seer.video.getVideoScene"
  },
  {
    "name": "seer.video.createVideoScene"
  },
  {
    "name": "seer.video.updateVideoScene"
  },
  {
    "name": "seer.video.deleteVideoScene"
  },
  {
    "name": "seer.trek.getState"
  },
  {
    "name": "seer.trek.nextStop"
  },
  {
    "name": "seer.trek.choose"
  },
  {
    "name": "seer.evolution.info"
  },
  {
    "name": "seer.evolution.updateConfig"
  },
  {
    "name": "seer.evolution.updateGameStats"
  },
  {
    "name": "seer.evolution.monitorChest"
  },
  {
    "name": "seer.evolution.monitorParties"
  },
  {
    "name": "seer.evolution.getParties"
  },
  {
    "name": "seer.evolution.createParty"
  },
  {
    "name": "seer.evolution.joinParty"
  },
  {
    "name": "seer.evolution.leaveParty"
  },
  {
    "name": "seer.evolution.updateSettings"
  },
  {
    "name": "seer.evolution.getPayments"
  },
  {
    "name": "seer.evolution.processPayments"
  },
  {
    "name": "seer.evolution.cancelPaymentRequest"
  },
  {
    "name": "seer.evolution.createPaymentRequest"
  },
  {
    "name": "seer.evolution.saveRound"
  },
  {
    "name": "seer.evolution.interact"
  },
  {
    "name": "seer.evolution.getScene"
  },
  {
    "name": "seer.infinite.saveRound"
  },
  {
    "name": "seer.infinite.interact"
  },
  {
    "name": "seer.infinite.getScene"
  },
  {
    "name": "seer.oasis.getPatrons"
  },
  {
    "name": "seer.oasis.interact"
  },
  {
    "name": "seer.oasis.getScene"
  },
  {
    "name": "seer.isles.saveRound"
  },
  {
    "name": "seer.isles.interact"
  },
  {
    "name": "seer.isles.getScene"
  },
  {
    "name": "seer.novelist.getProject"
  },
  {
    "name": "seer.novelist.updatePresence"
  },
  {
    "name": "seer.novelist.saveProject"
  },
  {
    "name": "seer.novelist.generateRevision"
  },
  {
    "name": "seer.novelist.resolveRevision"
  },
  {
    "name": "seer.novelist.createSnapshot"
  },
  {
    "name": "seer.novelist.restoreSnapshot"
  },
  {
    "name": "seer.novelist.runAnalysis"
  },
  {
    "name": "seer.novelist.exportEdition"
  },
  {
    "name": "seer.novelist.searchCanon"
  },
  {
    "name": "seer.info"
  },
  {
    "name": "seer.auth"
  },
  {
    "name": "seer.banProfile"
  },
  {
    "name": "seer-prd.area.getArea"
  },
  {
    "name": "seer-prd.area.getAreas"
  },
  {
    "name": "seer-prd.area.saveArea"
  },
  {
    "name": "seer-prd.area.getAreaLandmark"
  },
  {
    "name": "seer-prd.area.createAreaLandmark"
  },
  {
    "name": "seer-prd.area.updateAreaLandmark"
  },
  {
    "name": "seer-prd.area.getAreaType"
  },
  {
    "name": "seer-prd.area.createAreaType"
  },
  {
    "name": "seer-prd.area.updateAreaType"
  },
  {
    "name": "seer-prd.asset.getAsset"
  },
  {
    "name": "seer-prd.asset.createAsset"
  },
  {
    "name": "seer-prd.asset.updateAsset"
  },
  {
    "name": "seer-prd.asset.getAssetLicense"
  },
  {
    "name": "seer-prd.asset.createAssetLicense"
  },
  {
    "name": "seer-prd.asset.updateAssetLicense"
  },
  {
    "name": "seer-prd.chain.getChain"
  },
  {
    "name": "seer-prd.chain.createChain"
  },
  {
    "name": "seer-prd.chain.updateChain"
  },
  {
    "name": "seer-prd.chain.getChainContract"
  },
  {
    "name": "seer-prd.chain.createChainContract"
  },
  {
    "name": "seer-prd.chain.updateChainContract"
  },
  {
    "name": "seer-prd.chain.getChainToken"
  },
  {
    "name": "seer-prd.chain.createChainToken"
  },
  {
    "name": "seer-prd.chain.updateChainToken"
  },
  {
    "name": "seer-prd.chain.getChainTransaction"
  },
  {
    "name": "seer-prd.chain.createChainTransaction"
  },
  {
    "name": "seer-prd.chain.updateChainTransaction"
  },
  {
    "name": "seer-prd.character.getCharacterInventory"
  },
  {
    "name": "seer-prd.character.syncCharacterInventory"
  },
  {
    "name": "seer-prd.character.applyCharacterInventoryPatch"
  },
  {
    "name": "seer-prd.character.setActiveCharacter"
  },
  {
    "name": "seer-prd.character.exchangeCharacterItem"
  },
  {
    "name": "seer-prd.character.getCharacterData"
  },
  {
    "name": "seer-prd.character.getCharacter"
  },
  {
    "name": "seer-prd.character.getCharacters"
  },
  {
    "name": "seer-prd.character.saveCharacters"
  },
  {
    "name": "seer-prd.character.updateCharacter"
  },
  {
    "name": "seer-prd.character.getCharacterAbility"
  },
  {
    "name": "seer-prd.character.createCharacterAbility"
  },
  {
    "name": "seer-prd.character.updateCharacterAbility"
  },
  {
    "name": "seer-prd.character.getCharacterAttribute"
  },
  {
    "name": "seer-prd.character.createCharacterAttribute"
  },
  {
    "name": "seer-prd.character.updateCharacterAttribute"
  },
  {
    "name": "seer-prd.character.getCharacterType"
  },
  {
    "name": "seer-prd.character.createCharacterType"
  },
  {
    "name": "seer-prd.character.updateCharacterType"
  },
  {
    "name": "seer-prd.character.getCharacterClass"
  },
  {
    "name": "seer-prd.character.createCharacterClass"
  },
  {
    "name": "seer-prd.character.updateCharacterClass"
  },
  {
    "name": "seer-prd.character.getCharacterRace"
  },
  {
    "name": "seer-prd.character.createCharacterRace"
  },
  {
    "name": "seer-prd.character.updateCharacterRace"
  },
  {
    "name": "seer-prd.character.getCharacterGender"
  },
  {
    "name": "seer-prd.character.createCharacterGender"
  },
  {
    "name": "seer-prd.character.updateCharacterGender"
  },
  {
    "name": "seer-prd.character.getCharacterPersonality"
  },
  {
    "name": "seer-prd.character.createCharacterPersonality"
  },
  {
    "name": "seer-prd.character.updateCharacterPersonality"
  },
  {
    "name": "seer-prd.character.getCharacterTitle"
  },
  {
    "name": "seer-prd.character.createCharacterTitle"
  },
  {
    "name": "seer-prd.character.updateCharacterTitle"
  },
  {
    "name": "seer-prd.character.getCharacterFaction"
  },
  {
    "name": "seer-prd.character.getCharacterFactions"
  },
  {
    "name": "seer-prd.character.createCharacterFaction"
  },
  {
    "name": "seer-prd.character.updateCharacterFaction"
  },
  {
    "name": "seer-prd.character.getCharacterNameChoice"
  },
  {
    "name": "seer-prd.character.createCharacterNameChoice"
  },
  {
    "name": "seer-prd.character.updateCharacterNameChoice"
  },
  {
    "name": "seer-prd.chat.getChatGroup"
  },
  {
    "name": "seer-prd.chat.getChatGroups"
  },
  {
    "name": "seer-prd.chat.createChatGroup"
  },
  {
    "name": "seer-prd.chat.updateChatGroup"
  },
  {
    "name": "seer-prd.chat.getChatMessage"
  },
  {
    "name": "seer-prd.chat.getChatMessages"
  },
  {
    "name": "seer-prd.chat.createChatMessage"
  },
  {
    "name": "seer-prd.chat.updateChatMessage"
  },
  {
    "name": "seer-prd.collection.getCollectibleCollection"
  },
  {
    "name": "seer-prd.collection.createCollectibleCollection"
  },
  {
    "name": "seer-prd.collection.updateCollectibleCollection"
  },
  {
    "name": "seer-prd.collection.getCollectibleCardBox"
  },
  {
    "name": "seer-prd.collection.createCollectibleCardBox"
  },
  {
    "name": "seer-prd.collection.updateCollectibleCardBox"
  },
  {
    "name": "seer-prd.collection.getCollectibleCardPack"
  },
  {
    "name": "seer-prd.collection.createCollectibleCardPack"
  },
  {
    "name": "seer-prd.collection.updateCollectibleCardPack"
  },
  {
    "name": "seer-prd.collection.getCollectibleCard"
  },
  {
    "name": "seer-prd.collection.createCollectibleCard"
  },
  {
    "name": "seer-prd.collection.updateCollectibleCard"
  },
  {
    "name": "seer-prd.core.getConversation"
  },
  {
    "name": "seer-prd.core.createConversation"
  },
  {
    "name": "seer-prd.core.updateConversation"
  },
  {
    "name": "seer-prd.core.getConversations"
  },
  {
    "name": "seer-prd.core.getConversationMessage"
  },
  {
    "name": "seer-prd.core.getConversationMessages"
  },
  {
    "name": "seer-prd.core.createConversationMessage"
  },
  {
    "name": "seer-prd.core.updateConversationMessage"
  },
  {
    "name": "seer-prd.core.claimConversationMessage"
  },
  {
    "name": "seer-prd.core.setConversationMessageStar"
  },
  {
    "name": "seer-prd.core.markConversationRead"
  },
  {
    "name": "seer-prd.core.archiveReadConversations"
  },
  {
    "name": "seer-prd.core.readAndClaimLatestMail"
  },
  {
    "name": "seer-prd.core.distributeSantaChristmasTicketToProfile"
  },
  {
    "name": "seer-prd.core.distributeSantaChristmasTicket"
  },
  {
    "name": "seer-prd.core.play"
  },
  {
    "name": "seer-prd.core.syncGetPayloadsSince"
  },
  {
    "name": "seer-prd.core.ingestWarpFlowActivity"
  },
  {
    "name": "seer-prd.core.getWarpFlowActivity"
  },
  {
    "name": "seer-prd.core.updateSettings"
  },
  {
    "name": "seer-prd.core.ask"
  },
  {
    "name": "seer-prd.core.authorize"
  },
  {
    "name": "seer-prd.core.getAccount"
  },
  {
    "name": "seer-prd.core.getAccounts"
  },
  {
    "name": "seer-prd.core.createAccount"
  },
  {
    "name": "seer-prd.core.updateAccount"
  },
  {
    "name": "seer-prd.core.getAchievement"
  },
  {
    "name": "seer-prd.core.getAchievements"
  },
  {
    "name": "seer-prd.core.createAchievement"
  },
  {
    "name": "seer-prd.core.updateAchievement"
  },
  {
    "name": "seer-prd.core.getAct"
  },
  {
    "name": "seer-prd.core.getActs"
  },
  {
    "name": "seer-prd.core.createAct"
  },
  {
    "name": "seer-prd.core.updateAct"
  },
  {
    "name": "seer-prd.core.getAgent"
  },
  {
    "name": "seer-prd.core.createAgent"
  },
  {
    "name": "seer-prd.core.updateAgent"
  },
  {
    "name": "seer-prd.core.getApplication"
  },
  {
    "name": "seer-prd.core.createApplication"
  },
  {
    "name": "seer-prd.core.updateApplication"
  },
  {
    "name": "seer-prd.core.getBadge"
  },
  {
    "name": "seer-prd.core.createBadge"
  },
  {
    "name": "seer-prd.core.updateBadge"
  },
  {
    "name": "seer-prd.core.getBattlePass"
  },
  {
    "name": "seer-prd.core.createBattlePass"
  },
  {
    "name": "seer-prd.core.updateBattlePass"
  },
  {
    "name": "seer-prd.core.getBiome"
  },
  {
    "name": "seer-prd.core.createBiome"
  },
  {
    "name": "seer-prd.core.updateBiome"
  },
  {
    "name": "seer-prd.core.getBiomeFeature"
  },
  {
    "name": "seer-prd.core.createBiomeFeature"
  },
  {
    "name": "seer-prd.core.updateBiomeFeature"
  },
  {
    "name": "seer-prd.core.getBounty"
  },
  {
    "name": "seer-prd.core.createBounty"
  },
  {
    "name": "seer-prd.core.updateBounty"
  },
  {
    "name": "seer-prd.core.getCollection"
  },
  {
    "name": "seer-prd.core.createCollection"
  },
  {
    "name": "seer-prd.core.updateCollection"
  },
  {
    "name": "seer-prd.core.getComment"
  },
  {
    "name": "seer-prd.core.createComment"
  },
  {
    "name": "seer-prd.core.updateComment"
  },
  {
    "name": "seer-prd.core.getCommunity"
  },
  {
    "name": "seer-prd.core.createCommunity"
  },
  {
    "name": "seer-prd.core.updateCommunity"
  },
  {
    "name": "seer-prd.core.getCompany"
  },
  {
    "name": "seer-prd.core.createCompany"
  },
  {
    "name": "seer-prd.core.updateCompany"
  },
  {
    "name": "seer-prd.core.getData"
  },
  {
    "name": "seer-prd.core.createData"
  },
  {
    "name": "seer-prd.core.updateData"
  },
  {
    "name": "seer-prd.core.getDiscussion"
  },
  {
    "name": "seer-prd.core.createDiscussion"
  },
  {
    "name": "seer-prd.core.updateDiscussion"
  },
  {
    "name": "seer-prd.core.getEnergy"
  },
  {
    "name": "seer-prd.core.getEnergies"
  },
  {
    "name": "seer-prd.core.createEnergy"
  },
  {
    "name": "seer-prd.core.updateEnergy"
  },
  {
    "name": "seer-prd.core.getEvent"
  },
  {
    "name": "seer-prd.core.createEvent"
  },
  {
    "name": "seer-prd.core.updateEvent"
  },
  {
    "name": "seer-prd.core.getFile"
  },
  {
    "name": "seer-prd.core.createFile"
  },
  {
    "name": "seer-prd.core.updateFile"
  },
  {
    "name": "seer-prd.core.getGalaxy"
  },
  {
    "name": "seer-prd.core.createGalaxy"
  },
  {
    "name": "seer-prd.core.updateGalaxy"
  },
  {
    "name": "seer-prd.core.getGuide"
  },
  {
    "name": "seer-prd.core.createGuide"
  },
  {
    "name": "seer-prd.core.updateGuide"
  },
  {
    "name": "seer-prd.core.getIdea"
  },
  {
    "name": "seer-prd.core.createIdea"
  },
  {
    "name": "seer-prd.core.updateIdea"
  },
  {
    "name": "seer-prd.core.getLeaderboard"
  },
  {
    "name": "seer-prd.core.createLeaderboard"
  },
  {
    "name": "seer-prd.core.updateLeaderboard"
  },
  {
    "name": "seer-prd.core.getLog"
  },
  {
    "name": "seer-prd.core.createLog"
  },
  {
    "name": "seer-prd.core.updateLog"
  },
  {
    "name": "seer-prd.core.getLore"
  },
  {
    "name": "seer-prd.core.createLore"
  },
  {
    "name": "seer-prd.core.updateLore"
  },
  {
    "name": "seer-prd.core.getMemory"
  },
  {
    "name": "seer-prd.core.createMemory"
  },
  {
    "name": "seer-prd.core.updateMemory"
  },
  {
    "name": "seer-prd.core.ingestMemoryLedgerRecord"
  },
  {
    "name": "seer-prd.core.getMemoryLedgerRecords"
  },
  {
    "name": "seer-prd.core.getMemoryTelemetrySummary"
  },
  {
    "name": "seer-prd.core.getMessage"
  },
  {
    "name": "seer-prd.core.createMessage"
  },
  {
    "name": "seer-prd.core.updateMessage"
  },
  {
    "name": "seer-prd.core.getMetaverse"
  },
  {
    "name": "seer-prd.core.createMetaverse"
  },
  {
    "name": "seer-prd.core.updateMetaverse"
  },
  {
    "name": "seer-prd.core.getNewsArticle"
  },
  {
    "name": "seer-prd.core.createNewsArticle"
  },
  {
    "name": "seer-prd.core.updateNewsArticle"
  },
  {
    "name": "seer-prd.core.getNpc"
  },
  {
    "name": "seer-prd.core.createNpc"
  },
  {
    "name": "seer-prd.core.updateNpc"
  },
  {
    "name": "seer-prd.core.getOffer"
  },
  {
    "name": "seer-prd.core.createOffer"
  },
  {
    "name": "seer-prd.core.updateOffer"
  },
  {
    "name": "seer-prd.core.getOmniverse"
  },
  {
    "name": "seer-prd.core.createOmniverse"
  },
  {
    "name": "seer-prd.core.updateOmniverse"
  },
  {
    "name": "seer-prd.core.getOrder"
  },
  {
    "name": "seer-prd.core.createOrder"
  },
  {
    "name": "seer-prd.core.updateOrder"
  },
  {
    "name": "seer-prd.core.getPayment"
  },
  {
    "name": "seer-prd.core.createPayment"
  },
  {
    "name": "seer-prd.core.updatePayment"
  },
  {
    "name": "seer-prd.core.getPermission"
  },
  {
    "name": "seer-prd.core.createPermission"
  },
  {
    "name": "seer-prd.core.updatePermission"
  },
  {
    "name": "seer-prd.core.getPerson"
  },
  {
    "name": "seer-prd.core.createPerson"
  },
  {
    "name": "seer-prd.core.updatePerson"
  },
  {
    "name": "seer-prd.core.getPlanet"
  },
  {
    "name": "seer-prd.core.createPlanet"
  },
  {
    "name": "seer-prd.core.updatePlanet"
  },
  {
    "name": "seer-prd.core.getPoll"
  },
  {
    "name": "seer-prd.core.createPoll"
  },
  {
    "name": "seer-prd.core.updatePoll"
  },
  {
    "name": "seer-prd.core.getProject"
  },
  {
    "name": "seer-prd.core.createProject"
  },
  {
    "name": "seer-prd.core.updateProject"
  },
  {
    "name": "seer-prd.core.getRepository"
  },
  {
    "name": "seer-prd.core.getRepositories"
  },
  {
    "name": "seer-prd.core.createRepository"
  },
  {
    "name": "seer-prd.core.updateRepository"
  },
  {
    "name": "seer-prd.core.upsertRepository"
  },
  {
    "name": "seer-prd.core.getProductFeature"
  },
  {
    "name": "seer-prd.core.getProductFeatures"
  },
  {
    "name": "seer-prd.core.createProductFeature"
  },
  {
    "name": "seer-prd.core.updateProductFeature"
  },
  {
    "name": "seer-prd.core.upsertProductFeature"
  },
  {
    "name": "seer-prd.core.getRepositoryCommit"
  },
  {
    "name": "seer-prd.core.getRepositoryCommits"
  },
  {
    "name": "seer-prd.core.createRepositoryCommit"
  },
  {
    "name": "seer-prd.core.updateRepositoryCommit"
  },
  {
    "name": "seer-prd.core.upsertRepositoryCommit"
  },
  {
    "name": "seer-prd.core.getIssueEmbedding"
  },
  {
    "name": "seer-prd.core.getIssueEmbeddings"
  },
  {
    "name": "seer-prd.core.upsertIssueEmbedding"
  },
  {
    "name": "seer-prd.core.upsertIssueEmbeddingsBatch"
  },
  {
    "name": "seer-prd.core.searchIssueEmbeddings"
  },
  {
    "name": "seer-prd.core.getProjectEmbedding"
  },
  {
    "name": "seer-prd.core.getProjectEmbeddings"
  },
  {
    "name": "seer-prd.core.upsertProjectEmbedding"
  },
  {
    "name": "seer-prd.core.upsertProjectEmbeddingsBatch"
  },
  {
    "name": "seer-prd.core.searchProjectEmbeddings"
  },
  {
    "name": "seer-prd.core.getProductEmbedding"
  },
  {
    "name": "seer-prd.core.getProductEmbeddings"
  },
  {
    "name": "seer-prd.core.upsertProductEmbedding"
  },
  {
    "name": "seer-prd.core.upsertProductEmbeddingsBatch"
  },
  {
    "name": "seer-prd.core.searchProductEmbeddings"
  },
  {
    "name": "seer-prd.core.getAgentEmbedding"
  },
  {
    "name": "seer-prd.core.getAgentEmbeddings"
  },
  {
    "name": "seer-prd.core.upsertAgentEmbedding"
  },
  {
    "name": "seer-prd.core.upsertAgentEmbeddingsBatch"
  },
  {
    "name": "seer-prd.core.searchAgentEmbeddings"
  },
  {
    "name": "seer-prd.core.getSessionContext"
  },
  {
    "name": "seer-prd.core.getSessionContexts"
  },
  {
    "name": "seer-prd.core.upsertSessionContext"
  },
  {
    "name": "seer-prd.core.upsertSessionContextEdge"
  },
  {
    "name": "seer-prd.core.getActiveSessionContextsByRepoAndAgent"
  },
  {
    "name": "seer-prd.core.getProposal"
  },
  {
    "name": "seer-prd.core.createProposal"
  },
  {
    "name": "seer-prd.core.updateProposal"
  },
  {
    "name": "seer-prd.core.getQuest"
  },
  {
    "name": "seer-prd.core.createQuest"
  },
  {
    "name": "seer-prd.core.updateQuest"
  },
  {
    "name": "seer-prd.core.getRating"
  },
  {
    "name": "seer-prd.core.createRating"
  },
  {
    "name": "seer-prd.core.updateRating"
  },
  {
    "name": "seer-prd.core.getRealm"
  },
  {
    "name": "seer-prd.core.getRealms"
  },
  {
    "name": "seer-prd.core.createRealm"
  },
  {
    "name": "seer-prd.core.updateRealm"
  },
  {
    "name": "seer-prd.core.getRealmEvent"
  },
  {
    "name": "seer-prd.core.getRealmEvents"
  },
  {
    "name": "seer-prd.core.createRealmEvent"
  },
  {
    "name": "seer-prd.core.updateRealmEvent"
  },
  {
    "name": "seer-prd.core.getRevision"
  },
  {
    "name": "seer-prd.core.createRevision"
  },
  {
    "name": "seer-prd.core.updateRevision"
  },
  {
    "name": "seer-prd.core.getReferral"
  },
  {
    "name": "seer-prd.core.createReferral"
  },
  {
    "name": "seer-prd.core.updateReferral"
  },
  {
    "name": "seer-prd.core.getReview"
  },
  {
    "name": "seer-prd.core.createReview"
  },
  {
    "name": "seer-prd.core.updateReview"
  },
  {
    "name": "seer-prd.core.getRole"
  },
  {
    "name": "seer-prd.core.createRole"
  },
  {
    "name": "seer-prd.core.updateRole"
  },
  {
    "name": "seer-prd.core.getSeason"
  },
  {
    "name": "seer-prd.core.createSeason"
  },
  {
    "name": "seer-prd.core.updateSeason"
  },
  {
    "name": "seer-prd.core.getRealmShard"
  },
  {
    "name": "seer-prd.core.getRealmShards"
  },
  {
    "name": "seer-prd.core.createRealmShard"
  },
  {
    "name": "seer-prd.core.updateRealmShard"
  },
  {
    "name": "seer-prd.core.getSession"
  },
  {
    "name": "seer-prd.core.createSession"
  },
  {
    "name": "seer-prd.core.updateSession"
  },
  {
    "name": "seer-prd.core.getSolarSystem"
  },
  {
    "name": "seer-prd.core.createSolarSystem"
  },
  {
    "name": "seer-prd.core.updateSolarSystem"
  },
  {
    "name": "seer-prd.core.getStar"
  },
  {
    "name": "seer-prd.core.createStar"
  },
  {
    "name": "seer-prd.core.updateStar"
  },
  {
    "name": "seer-prd.core.getStash"
  },
  {
    "name": "seer-prd.core.createStash"
  },
  {
    "name": "seer-prd.core.updateStash"
  },
  {
    "name": "seer-prd.core.getStock"
  },
  {
    "name": "seer-prd.core.createStock"
  },
  {
    "name": "seer-prd.core.updateStock"
  },
  {
    "name": "seer-prd.core.getSuggestion"
  },
  {
    "name": "seer-prd.core.createSuggestion"
  },
  {
    "name": "seer-prd.core.updateSuggestion"
  },
  {
    "name": "seer-prd.core.getTag"
  },
  {
    "name": "seer-prd.core.createTag"
  },
  {
    "name": "seer-prd.core.updateTag"
  },
  {
    "name": "seer-prd.core.getTeam"
  },
  {
    "name": "seer-prd.core.getTeams"
  },
  {
    "name": "seer-prd.core.createTeam"
  },
  {
    "name": "seer-prd.core.updateTeam"
  },
  {
    "name": "seer-prd.core.getTournament"
  },
  {
    "name": "seer-prd.core.getTournaments"
  },
  {
    "name": "seer-prd.core.createTournament"
  },
  {
    "name": "seer-prd.core.updateTournament"
  },
  {
    "name": "seer-prd.core.getTrade"
  },
  {
    "name": "seer-prd.core.getTrades"
  },
  {
    "name": "seer-prd.core.createTrade"
  },
  {
    "name": "seer-prd.core.updateTrade"
  },
  {
    "name": "seer-prd.core.getUniverse"
  },
  {
    "name": "seer-prd.core.createUniverse"
  },
  {
    "name": "seer-prd.core.updateUniverse"
  },
  {
    "name": "seer-prd.core.getValidator"
  },
  {
    "name": "seer-prd.core.createValidator"
  },
  {
    "name": "seer-prd.core.updateValidator"
  },
  {
    "name": "seer-prd.core.getVote"
  },
  {
    "name": "seer-prd.core.createVote"
  },
  {
    "name": "seer-prd.core.updateVote"
  },
  {
    "name": "seer-prd.core.getWorldEvent"
  },
  {
    "name": "seer-prd.core.createWorldEvent"
  },
  {
    "name": "seer-prd.core.updateWorldEvent"
  },
  {
    "name": "seer-prd.core.getWorldRecord"
  },
  {
    "name": "seer-prd.core.createWorldRecord"
  },
  {
    "name": "seer-prd.core.updateWorldRecord"
  },
  {
    "name": "seer-prd.core.info"
  },
  {
    "name": "seer-prd.core.stats"
  },
  {
    "name": "seer-prd.game.getGame"
  },
  {
    "name": "seer-prd.game.getGames"
  },
  {
    "name": "seer-prd.game.createGame"
  },
  {
    "name": "seer-prd.game.updateGame"
  },
  {
    "name": "seer-prd.game.getGameStat"
  },
  {
    "name": "seer-prd.game.getGameStats"
  },
  {
    "name": "seer-prd.game.createGameStat"
  },
  {
    "name": "seer-prd.game.updateGameStat"
  },
  {
    "name": "seer-prd.game.getEra"
  },
  {
    "name": "seer-prd.game.getEras"
  },
  {
    "name": "seer-prd.game.createEra"
  },
  {
    "name": "seer-prd.game.updateEra"
  },
  {
    "name": "seer-prd.game.deleteEra"
  },
  {
    "name": "seer-prd.interface.getInterface"
  },
  {
    "name": "seer-prd.interface.createInterface"
  },
  {
    "name": "seer-prd.interface.updateInterface"
  },
  {
    "name": "seer-prd.interface.deleteInterface"
  },
  {
    "name": "seer-prd.interface.getInterfaces"
  },
  {
    "name": "seer-prd.interface.getInterfaceGroup"
  },
  {
    "name": "seer-prd.interface.getInterfaceGroups"
  },
  {
    "name": "seer-prd.interface.createInterfaceGroup"
  },
  {
    "name": "seer-prd.interface.updateInterfaceGroup"
  },
  {
    "name": "seer-prd.interface.getInterfaceComponent"
  },
  {
    "name": "seer-prd.interface.createInterfaceComponent"
  },
  {
    "name": "seer-prd.interface.updateInterfaceComponent"
  },
  {
    "name": "seer-prd.interface.publishInterface"
  },
  {
    "name": "seer-prd.interface.deactivateInterface"
  },
  {
    "name": "seer-prd.interface.resetInterface"
  },
  {
    "name": "seer-prd.interface.acceptInterfaceSubmission"
  },
  {
    "name": "seer-prd.interface.createInterfaceDraft"
  },
  {
    "name": "seer-prd.item.getItem"
  },
  {
    "name": "seer-prd.item.getItems"
  },
  {
    "name": "seer-prd.item.createItem"
  },
  {
    "name": "seer-prd.item.updateItem"
  },
  {
    "name": "seer-prd.item.getItemAttribute"
  },
  {
    "name": "seer-prd.item.createItemAttribute"
  },
  {
    "name": "seer-prd.item.updateItemAttribute"
  },
  {
    "name": "seer-prd.item.getItemTransmute"
  },
  {
    "name": "seer-prd.item.createItemTransmute"
  },
  {
    "name": "seer-prd.item.updateItemTransmute"
  },
  {
    "name": "seer-prd.job.getJob"
  },
  {
    "name": "seer-prd.job.createJob"
  },
  {
    "name": "seer-prd.job.updateJob"
  },
  {
    "name": "seer-prd.job.updateMetrics"
  },
  {
    "name": "seer-prd.market.getMarket"
  },
  {
    "name": "seer-prd.market.createMarket"
  },
  {
    "name": "seer-prd.market.updateMarket"
  },
  {
    "name": "seer-prd.market.getMarketPair"
  },
  {
    "name": "seer-prd.market.createMarketPair"
  },
  {
    "name": "seer-prd.market.updateMarketPair"
  },
  {
    "name": "seer-prd.market.getMarketExchange"
  },
  {
    "name": "seer-prd.market.createMarketExchange"
  },
  {
    "name": "seer-prd.market.updateMarketExchange"
  },
  {
    "name": "seer-prd.market.getMarketListing"
  },
  {
    "name": "seer-prd.market.createMarketListing"
  },
  {
    "name": "seer-prd.market.updateMarketListing"
  },
  {
    "name": "seer-prd.market.deleteMarketListing"
  },
  {
    "name": "seer-prd.market.getMarketListings"
  },
  {
    "name": "seer-prd.product.getProduct"
  },
  {
    "name": "seer-prd.product.createProduct"
  },
  {
    "name": "seer-prd.product.updateProduct"
  },
  {
    "name": "seer-prd.product.getProductDLC"
  },
  {
    "name": "seer-prd.product.createProductDLC"
  },
  {
    "name": "seer-prd.product.updateProductDLC"
  },
  {
    "name": "seer-prd.product.getProductBundle"
  },
  {
    "name": "seer-prd.product.createProductBundle"
  },
  {
    "name": "seer-prd.product.updateProductBundle"
  },
  {
    "name": "seer-prd.product.getProductReview"
  },
  {
    "name": "seer-prd.product.createProductReview"
  },
  {
    "name": "seer-prd.product.updateProductReview"
  },
  {
    "name": "seer-prd.profile.setProfileMode"
  },
  {
    "name": "seer-prd.profile.me"
  },
  {
    "name": "seer-prd.profile.getProfile"
  },
  {
    "name": "seer-prd.profile.getProfiles"
  },
  {
    "name": "seer-prd.profile.createProfile"
  },
  {
    "name": "seer-prd.profile.updateProfile"
  },
  {
    "name": "seer-prd.profile.getProfileStats"
  },
  {
    "name": "seer-prd.profile.updateProfileSettings"
  },
  {
    "name": "seer-prd.raffle.getRaffle"
  },
  {
    "name": "seer-prd.raffle.createRaffle"
  },
  {
    "name": "seer-prd.raffle.updateRaffle"
  },
  {
    "name": "seer-prd.raffle.getRaffleRequirement"
  },
  {
    "name": "seer-prd.raffle.createRaffleRequirement"
  },
  {
    "name": "seer-prd.raffle.updateRaffleRequirement"
  },
  {
    "name": "seer-prd.raffle.getRaffleReward"
  },
  {
    "name": "seer-prd.raffle.createRaffleReward"
  },
  {
    "name": "seer-prd.raffle.updateRaffleReward"
  },
  {
    "name": "seer-prd.raffle.getRaffleEntry"
  },
  {
    "name": "seer-prd.raffle.createRaffleEntry"
  },
  {
    "name": "seer-prd.raffle.updateRaffleEntry"
  },
  {
    "name": "seer-prd.skill.getSkill"
  },
  {
    "name": "seer-prd.skill.createSkill"
  },
  {
    "name": "seer-prd.skill.updateSkill"
  },
  {
    "name": "seer-prd.skill.deleteSkill"
  },
  {
    "name": "seer-prd.skill.getSkillMod"
  },
  {
    "name": "seer-prd.skill.createSkillMod"
  },
  {
    "name": "seer-prd.skill.updateSkillMod"
  },
  {
    "name": "seer-prd.skill.deleteSkillMod"
  },
  {
    "name": "seer-prd.skill.getSkillClassification"
  },
  {
    "name": "seer-prd.skill.createSkillClassification"
  },
  {
    "name": "seer-prd.skill.updateSkillClassification"
  },
  {
    "name": "seer-prd.skill.deleteSkillClassification"
  },
  {
    "name": "seer-prd.skill.getSkillCondition"
  },
  {
    "name": "seer-prd.skill.createSkillCondition"
  },
  {
    "name": "seer-prd.skill.updateSkillCondition"
  },
  {
    "name": "seer-prd.skill.deleteSkillCondition"
  },
  {
    "name": "seer-prd.skill.getSkillStatusEffect"
  },
  {
    "name": "seer-prd.skill.createSkillStatusEffect"
  },
  {
    "name": "seer-prd.skill.updateSkillStatusEffect"
  },
  {
    "name": "seer-prd.skill.deleteSkillStatusEffect"
  },
  {
    "name": "seer-prd.skill.getSkillTree"
  },
  {
    "name": "seer-prd.skill.createSkillTree"
  },
  {
    "name": "seer-prd.skill.updateSkillTree"
  },
  {
    "name": "seer-prd.skill.deleteSkillTree"
  },
  {
    "name": "seer-prd.skill.getSkillTreeNode"
  },
  {
    "name": "seer-prd.skill.createSkillTreeNode"
  },
  {
    "name": "seer-prd.skill.updateSkillTreeNode"
  },
  {
    "name": "seer-prd.skill.deleteSkillTreeNode"
  },
  {
    "name": "seer-prd.video.getVideo"
  },
  {
    "name": "seer-prd.video.createVideo"
  },
  {
    "name": "seer-prd.video.updateVideo"
  },
  {
    "name": "seer-prd.video.deleteVideo"
  },
  {
    "name": "seer-prd.video.getVideoParticipant"
  },
  {
    "name": "seer-prd.video.createVideoParticipant"
  },
  {
    "name": "seer-prd.video.updateVideoParticipant"
  },
  {
    "name": "seer-prd.video.deleteVideoParticipant"
  },
  {
    "name": "seer-prd.video.getVideoDialogue"
  },
  {
    "name": "seer-prd.video.createVideoDialogue"
  },
  {
    "name": "seer-prd.video.updateVideoDialogue"
  },
  {
    "name": "seer-prd.video.deleteVideoDialogue"
  },
  {
    "name": "seer-prd.video.getVideoTranscript"
  },
  {
    "name": "seer-prd.video.createVideoTranscript"
  },
  {
    "name": "seer-prd.video.updateVideoTranscript"
  },
  {
    "name": "seer-prd.video.deleteVideoTranscript"
  },
  {
    "name": "seer-prd.video.getVideoScene"
  },
  {
    "name": "seer-prd.video.createVideoScene"
  },
  {
    "name": "seer-prd.video.updateVideoScene"
  },
  {
    "name": "seer-prd.video.deleteVideoScene"
  },
  {
    "name": "seer-prd.trek.getState"
  },
  {
    "name": "seer-prd.trek.nextStop"
  },
  {
    "name": "seer-prd.trek.choose"
  },
  {
    "name": "seer-prd.evolution.info"
  },
  {
    "name": "seer-prd.evolution.updateConfig"
  },
  {
    "name": "seer-prd.evolution.updateGameStats"
  },
  {
    "name": "seer-prd.evolution.monitorChest"
  },
  {
    "name": "seer-prd.evolution.monitorParties"
  },
  {
    "name": "seer-prd.evolution.getParties"
  },
  {
    "name": "seer-prd.evolution.createParty"
  },
  {
    "name": "seer-prd.evolution.joinParty"
  },
  {
    "name": "seer-prd.evolution.leaveParty"
  },
  {
    "name": "seer-prd.evolution.updateSettings"
  },
  {
    "name": "seer-prd.evolution.getPayments"
  },
  {
    "name": "seer-prd.evolution.processPayments"
  },
  {
    "name": "seer-prd.evolution.cancelPaymentRequest"
  },
  {
    "name": "seer-prd.evolution.createPaymentRequest"
  },
  {
    "name": "seer-prd.evolution.saveRound"
  },
  {
    "name": "seer-prd.evolution.interact"
  },
  {
    "name": "seer-prd.evolution.getScene"
  },
  {
    "name": "seer-prd.infinite.saveRound"
  },
  {
    "name": "seer-prd.infinite.interact"
  },
  {
    "name": "seer-prd.infinite.getScene"
  },
  {
    "name": "seer-prd.oasis.getPatrons"
  },
  {
    "name": "seer-prd.oasis.interact"
  },
  {
    "name": "seer-prd.oasis.getScene"
  },
  {
    "name": "seer-prd.isles.saveRound"
  },
  {
    "name": "seer-prd.isles.interact"
  },
  {
    "name": "seer-prd.isles.getScene"
  },
  {
    "name": "seer-prd.novelist.getProject"
  },
  {
    "name": "seer-prd.novelist.updatePresence"
  },
  {
    "name": "seer-prd.novelist.saveProject"
  },
  {
    "name": "seer-prd.novelist.generateRevision"
  },
  {
    "name": "seer-prd.novelist.resolveRevision"
  },
  {
    "name": "seer-prd.novelist.createSnapshot"
  },
  {
    "name": "seer-prd.novelist.restoreSnapshot"
  },
  {
    "name": "seer-prd.novelist.runAnalysis"
  },
  {
    "name": "seer-prd.novelist.exportEdition"
  },
  {
    "name": "seer-prd.novelist.searchCanon"
  },
  {
    "name": "seer-prd.info"
  },
  {
    "name": "seer-prd.auth"
  },
  {
    "name": "seer-prd.banProfile"
  },
  {
    "name": "evolution.auth"
  },
  {
    "name": "evolution.claimMaster"
  },
  {
    "name": "evolution.connectSeer"
  },
  {
    "name": "evolution.createShard"
  },
  {
    "name": "evolution.getShards"
  },
  {
    "name": "evolution.setConfig"
  },
  {
    "name": "evolution.ping"
  },
  {
    "name": "evolution.info"
  },
  {
    "name": "evolution.broadcast"
  },
  {
    "name": "evolution.addMod"
  },
  {
    "name": "evolution.removeMod"
  },
  {
    "name": "evolution.banClient"
  },
  {
    "name": "evolution.banUser"
  },
  {
    "name": "evolution.unbanClient"
  },
  {
    "name": "evolution.matchShard"
  },
  {
    "name": "evolution-prd.auth"
  },
  {
    "name": "evolution-prd.claimMaster"
  },
  {
    "name": "evolution-prd.connectSeer"
  },
  {
    "name": "evolution-prd.createShard"
  },
  {
    "name": "evolution-prd.getShards"
  },
  {
    "name": "evolution-prd.setConfig"
  },
  {
    "name": "evolution-prd.ping"
  },
  {
    "name": "evolution-prd.info"
  },
  {
    "name": "evolution-prd.broadcast"
  },
  {
    "name": "evolution-prd.addMod"
  },
  {
    "name": "evolution-prd.removeMod"
  },
  {
    "name": "evolution-prd.banClient"
  },
  {
    "name": "evolution-prd.banUser"
  },
  {
    "name": "evolution-prd.unbanClient"
  },
  {
    "name": "evolution-prd.matchShard"
  },
  {
    "name": "evolution-dev.auth"
  },
  {
    "name": "evolution-dev.claimMaster"
  },
  {
    "name": "evolution-dev.connectSeer"
  },
  {
    "name": "evolution-dev.createShard"
  },
  {
    "name": "evolution-dev.getShards"
  },
  {
    "name": "evolution-dev.setConfig"
  },
  {
    "name": "evolution-dev.ping"
  },
  {
    "name": "evolution-dev.info"
  },
  {
    "name": "evolution-dev.broadcast"
  },
  {
    "name": "evolution-dev.addMod"
  },
  {
    "name": "evolution-dev.removeMod"
  },
  {
    "name": "evolution-dev.banClient"
  },
  {
    "name": "evolution-dev.banUser"
  },
  {
    "name": "evolution-dev.unbanClient"
  },
  {
    "name": "evolution-dev.matchShard"
  }
];
