import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { router } from '../router';
import { getSummaryCommandDescription, type SummaryCommandInfo } from '../summary-cli';

const manifestPath = path.join(__dirname, '..', 'summary-manifest.generated.ts');
const procedures = (router as { _def?: { procedures?: Record<string, { _def?: { meta?: unknown } }> } })
  ._def?.procedures;

if (!procedures) {
  throw new Error('Unable to read router procedures for summary manifest generation');
}

const commands: SummaryCommandInfo[] = Object.entries(procedures).map(([name, procedure]) => ({
  name,
  description: getSummaryCommandDescription(procedure._def?.meta),
}));

const fileContents = `${[
  "import type { SummaryCommandInfo } from './summary-cli';",
  '',
  '// AUTO-GENERATED by scripts/generate-summary-manifest.ts. Do not edit manually.',
  `export const SUMMARY_COMMANDS: SummaryCommandInfo[] = ${JSON.stringify(commands, null, 2)};`,
  '',
].join('\n')}`;

writeFileSync(manifestPath, fileContents, 'utf-8');
